version: '3.8'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fitness_django
    restart: always
    env_file: .env
    depends_on:
      - postgres
    ports:
      - "8001:8000"

  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    container_name: fitness_db
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: fitness_nginx
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - django

  mailhog:
    image: mailhog/mailhog
    container_name: fitness_mail
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  postgres_data:
