# Use the official PostgreSQL image
FROM postgres:15

# Set environment variables for PostgreSQL
ENV POSTGRES_DB=fitness_db
ENV POSTGRES_USER=admin
ENV POSTGRES_PASSWORD=adminpassword

# Expose PostgreSQL port
EXPOSE 5432
